package vista;

import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class VistaAñadirUsuario extends javax.swing.JFrame {

    public VistaAñadirUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        SalirBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PasswordLabel3 = new javax.swing.JLabel();
        UsernameLabel1 = new javax.swing.JLabel();
        PasswordLabel2 = new javax.swing.JLabel();
        PasswordLabel5 = new javax.swing.JLabel();
        PasswordLabel4 = new javax.swing.JLabel();
        ContraseñaJTF = new javax.swing.JTextField();
        NombreUsuarioJTF = new javax.swing.JTextField();
        CurpJTF = new javax.swing.JTextField();
        ApellidosJTF = new javax.swing.JTextField();
        NombreJTF = new javax.swing.JTextField();
        AñadirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de boletos");
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalirBtn.setBackground(new java.awt.Color(0, 0, 0));
        SalirBtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        SalirBtn.setForeground(new java.awt.Color(255, 255, 255));
        SalirBtn.setText("Volver");
        SalirBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SalirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 73, 229, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordLabel3.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        PasswordLabel3.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel3.setText("Apellidos:");
        jPanel1.add(PasswordLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 172, -1, -1));

        UsernameLabel1.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        UsernameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel1.setText("Nombre:");
        jPanel1.add(UsernameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 139, -1, -1));

        PasswordLabel2.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        PasswordLabel2.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel2.setText("Curp:");
        jPanel1.add(PasswordLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        PasswordLabel5.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        PasswordLabel5.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel5.setText("Nombre de usuario:");
        jPanel1.add(PasswordLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 235, -1, -1));

        PasswordLabel4.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        PasswordLabel4.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel4.setText("Contraseña:");
        jPanel1.add(PasswordLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        ContraseñaJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaJTFActionPerformed(evt);
            }
        });
        jPanel1.add(ContraseñaJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 280, -1));
        jPanel1.add(NombreUsuarioJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 280, -1));
        jPanel1.add(CurpJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 274, -1));
        jPanel1.add(ApellidosJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 274, -1));
        jPanel1.add(NombreJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 274, -1));

        AñadirBtn.setBackground(new java.awt.Color(0, 0, 0));
        AñadirBtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        AñadirBtn.setForeground(new java.awt.Color(255, 255, 255));
        AñadirBtn.setText("Añadir usuario");
        AñadirBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        AñadirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AñadirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 175, 56));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirBtnActionPerformed

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirBtnActionPerformed

    private void ContraseñaJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaJTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAñadirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidosJTF;
    private javax.swing.JButton AñadirBtn;
    private javax.swing.JTextField ContraseñaJTF;
    private javax.swing.JTextField CurpJTF;
    private javax.swing.JTextField NombreJTF;
    private javax.swing.JTextField NombreUsuarioJTF;
    private javax.swing.JLabel PasswordLabel2;
    private javax.swing.JLabel PasswordLabel3;
    private javax.swing.JLabel PasswordLabel4;
    private javax.swing.JLabel PasswordLabel5;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JLabel UsernameLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    public JOptionPane getJOptionPane() {
        return jOptionPane1;
    }
    
    public JButton getjButton1() {
        return SalirBtn;
    }
    
    public JButton getjButton2(){
        return AñadirBtn;
    }

    public JTextField getjTextField1() {
        return NombreJTF;
    }

    public JTextField getjTextField2() {
        return ApellidosJTF;
    }
    
    public JTextField getjTextField3() {
        return CurpJTF;
    }
    
    public JTextField getjTextField4() {
        return NombreUsuarioJTF;
    }
    
    public JTextField getjTextField5() {
        return ContraseñaJTF;
    }
}
