package vista;

import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JTextField;

public class VistaMenúPrincipal extends javax.swing.JFrame {

    public VistaMenúPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModificarUsuarioBtn = new javax.swing.JButton();
        AñadirUsuarioBtn = new javax.swing.JButton();
        SalirBtn = new javax.swing.JButton();
        AdministrarObrasBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AdministrarFuncionesBtn = new javax.swing.JButton();
        VentaDeBoletos = new javax.swing.JButton();
        ReporteDeVentasBtn = new javax.swing.JButton();
        Fondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de boletos");
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModificarUsuarioBtn.setBackground(new java.awt.Color(0, 0, 0));
        ModificarUsuarioBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        ModificarUsuarioBtn.setForeground(new java.awt.Color(255, 255, 255));
        ModificarUsuarioBtn.setText("Modificar usuarios");
        ModificarUsuarioBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        ModificarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarUsuarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 180, 175, 56));

        AñadirUsuarioBtn.setBackground(new java.awt.Color(0, 0, 0));
        AñadirUsuarioBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        AñadirUsuarioBtn.setForeground(new java.awt.Color(255, 255, 255));
        AñadirUsuarioBtn.setText("Añadir usuario");
        AñadirUsuarioBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        AñadirUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirUsuarioBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AñadirUsuarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 180, 175, 56));

        SalirBtn.setBackground(new java.awt.Color(0, 0, 0));
        SalirBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        SalirBtn.setForeground(new java.awt.Color(255, 255, 255));
        SalirBtn.setText("Cerrar sesión");
        SalirBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SalirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 110, -1));

        AdministrarObrasBtn.setBackground(new java.awt.Color(0, 0, 0));
        AdministrarObrasBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        AdministrarObrasBtn.setForeground(new java.awt.Color(255, 255, 255));
        AdministrarObrasBtn.setText("Administrar obras");
        AdministrarObrasBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        AdministrarObrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministrarObrasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AdministrarObrasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 254, 175, 56));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú principal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 70, 362, 76));

        AdministrarFuncionesBtn.setBackground(new java.awt.Color(0, 0, 0));
        AdministrarFuncionesBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        AdministrarFuncionesBtn.setForeground(new java.awt.Color(255, 255, 255));
        AdministrarFuncionesBtn.setText("Administrar funciones");
        AdministrarFuncionesBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        getContentPane().add(AdministrarFuncionesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 254, 175, 56));

        VentaDeBoletos.setBackground(new java.awt.Color(0, 0, 0));
        VentaDeBoletos.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        VentaDeBoletos.setForeground(new java.awt.Color(255, 255, 255));
        VentaDeBoletos.setText("Vender boletos");
        VentaDeBoletos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        VentaDeBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaDeBoletosActionPerformed(evt);
            }
        });
        getContentPane().add(VentaDeBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 328, 175, 56));

        ReporteDeVentasBtn.setBackground(new java.awt.Color(0, 0, 0));
        ReporteDeVentasBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        ReporteDeVentasBtn.setForeground(new java.awt.Color(255, 255, 255));
        ReporteDeVentasBtn.setText("Reporte de ventas");
        ReporteDeVentasBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        ReporteDeVentasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteDeVentasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ReporteDeVentasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 328, 175, 56));

        Fondo.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarUsuarioBtnActionPerformed

    private void AñadirUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirUsuarioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirUsuarioBtnActionPerformed

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirBtnActionPerformed

    private void AdministrarObrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministrarObrasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdministrarObrasBtnActionPerformed

    private void VentaDeBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaDeBoletosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentaDeBoletosActionPerformed

    private void ReporteDeVentasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteDeVentasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReporteDeVentasBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenúPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdministrarFuncionesBtn;
    private javax.swing.JButton AdministrarObrasBtn;
    private javax.swing.JButton AñadirUsuarioBtn;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton ModificarUsuarioBtn;
    private javax.swing.JButton ReporteDeVentasBtn;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JButton VentaDeBoletos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    public JButton getjButton1() {
        return SalirBtn;
    }
    
    public JButton getjButton2() {
        return ModificarUsuarioBtn;
    }

    public JButton getjButton3() {
        return AñadirUsuarioBtn;
    }

    public JButton getjButton4() {
        return AdministrarObrasBtn;
    }

    public JButton getjButton5() {
        return AdministrarFuncionesBtn;
    }
    
    public JButton getjButton6() {
        return VentaDeBoletos;
    }
    
    public JButton getjButton7() {
        return ReporteDeVentasBtn;
    }
}
