package vista;

import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class VistaAñadirModificarObras extends javax.swing.JFrame {

    public VistaAñadirModificarObras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        SalirBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        UsernameLabel1 = new javax.swing.JLabel();
        JTF1 = new javax.swing.JTextField();
        PasswordLabel2 = new javax.swing.JLabel();
        JTF3 = new javax.swing.JTextField();
        JTF2 = new javax.swing.JTextField();
        PasswordLabel3 = new javax.swing.JLabel();
        JTF4 = new javax.swing.JTextField();
        PasswordLabel5 = new javax.swing.JLabel();
        JTF5 = new javax.swing.JTextField();
        JTF6 = new javax.swing.JTextField();
        JTF7 = new javax.swing.JTextField();
        PasswordLabel4 = new javax.swing.JLabel();
        PasswordLabel6 = new javax.swing.JLabel();
        PasswordLabel7 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        AñadirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de boletos");
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalirBtn.setBackground(new java.awt.Color(0, 0, 0));
        SalirBtn.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        SalirBtn.setForeground(new java.awt.Color(255, 255, 255));
        SalirBtn.setText("Volver");
        SalirBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SalirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nueva obra:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 44, 229, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        UsernameLabel1.setBackground(new java.awt.Color(0, 0, 0));
        UsernameLabel1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        UsernameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel1.setText("Nombre de la obra:");

        PasswordLabel2.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        PasswordLabel2.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel2.setText("Resumen temático:");

        JTF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF3ActionPerformed(evt);
            }
        });

        JTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF2ActionPerformed(evt);
            }
        });

        PasswordLabel3.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        PasswordLabel3.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel3.setText("Género:");

        JTF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF4ActionPerformed(evt);
            }
        });

        PasswordLabel5.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel5.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        PasswordLabel5.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel5.setText("Duración:");

        JTF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF5ActionPerformed(evt);
            }
        });

        JTF6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF6ActionPerformed(evt);
            }
        });

        JTF7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF7ActionPerformed(evt);
            }
        });

        PasswordLabel4.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        PasswordLabel4.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel4.setText("Primer actor principal:");

        PasswordLabel6.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel6.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        PasswordLabel6.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel6.setText("Segundo actor principal:");

        PasswordLabel7.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel7.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        PasswordLabel7.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel7.setText("Precio del boleto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordLabel2)
                    .addComponent(UsernameLabel1)
                    .addComponent(PasswordLabel3)
                    .addComponent(PasswordLabel5)
                    .addComponent(PasswordLabel4)
                    .addComponent(PasswordLabel6)
                    .addComponent(PasswordLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTF7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTF6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel1)
                    .addComponent(JTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 94, -1, -1));

        fondo.setBackground(new java.awt.Color(0, 0, 0));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AñadirBtn.setBackground(new java.awt.Color(0, 0, 0));
        AñadirBtn.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        AñadirBtn.setForeground(new java.awt.Color(255, 255, 255));
        AñadirBtn.setText("Añadir obra");
        AñadirBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        AñadirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirBtnActionPerformed(evt);
            }
        });
        fondo.add(AñadirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 250, 56));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirBtnActionPerformed

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirBtnActionPerformed

    private void JTF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF5ActionPerformed

    private void JTF6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF6ActionPerformed

    private void JTF7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF7ActionPerformed

    private void JTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF2ActionPerformed

    private void JTF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF4ActionPerformed

    private void JTF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAñadirModificarObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAñadirModificarObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAñadirModificarObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAñadirModificarObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAñadirModificarObras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirBtn;
    private javax.swing.JTextField JTF1;
    private javax.swing.JTextField JTF2;
    private javax.swing.JTextField JTF3;
    private javax.swing.JTextField JTF4;
    private javax.swing.JTextField JTF5;
    private javax.swing.JTextField JTF6;
    private javax.swing.JTextField JTF7;
    private javax.swing.JLabel PasswordLabel2;
    private javax.swing.JLabel PasswordLabel3;
    private javax.swing.JLabel PasswordLabel4;
    private javax.swing.JLabel PasswordLabel5;
    private javax.swing.JLabel PasswordLabel6;
    private javax.swing.JLabel PasswordLabel7;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JLabel UsernameLabel1;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    public JLabel getjTitle() {
        return jLabel1;
    }
    
    public JOptionPane getJOptionPane() {
        return jOptionPane1;
    }
    
    public JButton getjButton1() {
        return SalirBtn;
    }
    
    public JButton getjButton2(){
        return AñadirBtn;
    }

    public JTextField getjTextField1() {
        return JTF1;
    }

    public JTextField getjTextField2() {
        return JTF2;
    }
    
    public JTextField getjTextField3() {
        return JTF3;
    }
    
    public JTextField getjTextField4() {
        return JTF4;
    }
    
    public JTextField getjTextField5() {
        return JTF5;
    }
    
    public JTextField getjTextField6() {
        return JTF6;
    }
    
    public JTextField getjTextField7() {
        return JTF7;
    }
}
