package vista;

import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class VistaModificarUsuario extends javax.swing.JFrame {

    public VistaModificarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        NombreJTF = new javax.swing.JTextField();
        ApellidosJTF = new javax.swing.JTextField();
        ModificarUsuarioBtn = new javax.swing.JButton();
        SalirBtn = new javax.swing.JButton();
        PasswordLabel1 = new javax.swing.JLabel();
        CurpJTF = new javax.swing.JTextField();
        EliminarCuentaBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        UsernameLabel1 = new javax.swing.JLabel();
        PasswordLabel3 = new javax.swing.JLabel();
        PasswordLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PasswordLabel4 = new javax.swing.JLabel();
        ContraseñaNuevaJTF = new javax.swing.JTextField();
        NombreUsuarioNuevoJTF = new javax.swing.JTextField();
        PasswordLabel2 = new javax.swing.JLabel();
        CurpNuevoJTF = new javax.swing.JTextField();
        NombreNuevoJTF = new javax.swing.JTextField();
        ApellidosNuevoJTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de boletos");
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLabel.setBackground(new java.awt.Color(0, 0, 0));
        UsernameLabel.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel.setText("Nombre:");
        getContentPane().add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 189, -1, -1));

        PasswordLabel.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Apellidos:");
        getContentPane().add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, -1, -1));
        getContentPane().add(NombreJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 186, 200, -1));
        getContentPane().add(ApellidosJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 212, 200, -1));

        ModificarUsuarioBtn.setBackground(new java.awt.Color(0, 0, 0));
        ModificarUsuarioBtn.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        ModificarUsuarioBtn.setForeground(new java.awt.Color(255, 255, 255));
        ModificarUsuarioBtn.setText("Modificar usuario");
        ModificarUsuarioBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        ModificarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarUsuarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 318, 175, 56));

        SalirBtn.setBackground(new java.awt.Color(0, 0, 0));
        SalirBtn.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        SalirBtn.setForeground(new java.awt.Color(255, 255, 255));
        SalirBtn.setText("Volver");
        SalirBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SalirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 70, 40));

        PasswordLabel1.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel1.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        PasswordLabel1.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel1.setText("Curp:");
        getContentPane().add(PasswordLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 241, -1, -1));
        getContentPane().add(CurpJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 238, 200, -1));

        EliminarCuentaBtn.setBackground(new java.awt.Color(0, 0, 0));
        EliminarCuentaBtn.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        EliminarCuentaBtn.setForeground(new java.awt.Color(255, 255, 255));
        EliminarCuentaBtn.setText("Eliminar usuario");
        EliminarCuentaBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        EliminarCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCuentaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 318, 175, 56));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLabel1.setBackground(new java.awt.Color(0, 0, 0));
        UsernameLabel1.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        UsernameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel1.setText("Nombre:");
        jPanel1.add(UsernameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        PasswordLabel3.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel3.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        PasswordLabel3.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel3.setText("Apellidos:");
        jPanel1.add(PasswordLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        PasswordLabel5.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel5.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        PasswordLabel5.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel5.setText("Nombre de usuario:");
        jPanel1.add(PasswordLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 110, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevos datos:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 160, 50));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cuenta a modificar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 180, 50));

        PasswordLabel4.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel4.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        PasswordLabel4.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel4.setText("Contraseña:");
        jPanel1.add(PasswordLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        ContraseñaNuevaJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaNuevaJTFActionPerformed(evt);
            }
        });
        jPanel1.add(ContraseñaNuevaJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 200, -1));
        jPanel1.add(NombreUsuarioNuevoJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 200, -1));

        PasswordLabel2.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel2.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        PasswordLabel2.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel2.setText("Curp:");
        jPanel1.add(PasswordLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));
        jPanel1.add(CurpNuevoJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 200, -1));
        jPanel1.add(NombreNuevoJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 200, -1));
        jPanel1.add(ApellidosNuevoJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarUsuarioBtnActionPerformed

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirBtnActionPerformed

    private void EliminarCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCuentaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarCuentaBtnActionPerformed

    private void ContraseñaNuevaJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaNuevaJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaNuevaJTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModificarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidosJTF;
    private javax.swing.JTextField ApellidosNuevoJTF;
    private javax.swing.JTextField ContraseñaNuevaJTF;
    private javax.swing.JTextField CurpJTF;
    private javax.swing.JTextField CurpNuevoJTF;
    private javax.swing.JButton EliminarCuentaBtn;
    private javax.swing.JButton ModificarUsuarioBtn;
    private javax.swing.JTextField NombreJTF;
    private javax.swing.JTextField NombreNuevoJTF;
    private javax.swing.JTextField NombreUsuarioNuevoJTF;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JLabel PasswordLabel2;
    private javax.swing.JLabel PasswordLabel3;
    private javax.swing.JLabel PasswordLabel4;
    private javax.swing.JLabel PasswordLabel5;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel UsernameLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    public JOptionPane getJOptionPane() {
        return jOptionPane1;
    }
    
    public JButton getjButton1() {
        return SalirBtn;
    }

    public JButton getjButton2() {
        return EliminarCuentaBtn;
    }
    public JButton getjButton3(){
        return ModificarUsuarioBtn;
    }

    public JTextField getjTextField1() {
        return NombreJTF;
    }

    public JTextField getjTextField2() {
        return ApellidosJTF;
    }
    
    public JTextField getjTextField3() {
        return CurpJTF;
    }
    
     public JTextField getjTextField4() {
        return NombreNuevoJTF;
    }

    public JTextField getjTextField5() {
        return ApellidosNuevoJTF;
    }
    
    public JTextField getjTextField6() {
        return CurpNuevoJTF;
    }

    public JTextField getjTextField7() {
        return NombreUsuarioNuevoJTF;
    }
    
    public JTextField getjTextField8() {
        return ContraseñaNuevaJTF;
    }
}
